# Generated by Django 2.1.3 on 2019-01-13 04:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='first_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 4, 9, 56, 514048)),
        ),
        migrations.AlterField(
            model_name='userip',
            name='last_visit',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='userip',
            name='number_requests',
            field=models.IntegerField(default=0),
        ),
    ]
