# Generated by Django 2.1.3 on 2019-01-13 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20190113_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userip',
            name='first_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 13, 5, 40, 26, 544972)),
        ),
        migrations.AlterField(
            model_name='userip',
            name='number_requests',
            field=models.IntegerField(default=1),
        ),
    ]
