# Generated by Django 2.1.3 on 2019-01-17 01:50

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20190113_0540'),
    ]

    operations = [
        migrations.AddField(
            model_name='userip',
            name='host_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userip',
            name='first_visit',
            field=models.DateTimeField(default=datetime.datetime(2019, 1, 17, 1, 50, 6, 450589)),
        ),
    ]
